### ISSUE TITLE
TODO: Auton

### ISSUE THREAD

**Issue by caojohnny** [FRC4131/FIRSTDeepSpace2019-OLD#2]
Most recent commit from my fork has this info but I currently have the following to do:

- [x] Figure out the PID values
- [x] Create the auton paths to follow
- [ ] Figure out how position can be factored into the closed loop
- [ ] Actually test
- [ ] Check if Pathfinder has hardcoded the trajectory file dir

- [x] Infinite loop may not exit for NavX init
- [x] pidSet thread safety
